services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

    mem_limit: 250M
    memswap_limit: 350M
    cpus: 1

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo

    mem_limit: 250M
    memswap_limit: 350M
    cpus: 1